In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_sas('/Users/jhli/Documents/umich/mdst/day1/P_DEMO.XPT')

In [7]:
df.shape

(15560, 29)

In [11]:
df['RIDAGEYR'].mean()

33.742480719794344

In [61]:
df[df['RIDRETH1'] == 4.0]

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,DMDBORN4,...,FIAINTRP,MIALANG,MIAPROXY,MIAINTRP,AIALANGA,WTINTPRP,WTMECPRP,SDMVPSU,SDMVSTRA,INDFMPIR
7,109270.0,66.0,2.0,2.0,1.100000e+01,NaN,4.0,4.0,1.0,1.0,...,2.0,1.0,2.0,2.0,NaN,4613.057696,4886.930378,1.0,150.0,1.880000e+00
13,109276.0,66.0,2.0,1.0,5.397605e-79,2.0,4.0,4.0,2.0,1.0,...,2.0,NaN,NaN,NaN,NaN,1652.540459,1810.573063,1.0,171.0,5.397605e-79
22,109285.0,66.0,2.0,1.0,1.600000e+01,NaN,4.0,4.0,2.0,1.0,...,2.0,1.0,2.0,2.0,1.0,27778.645672,29931.009310,1.0,163.0,2.390000e+00
27,109290.0,66.0,2.0,2.0,6.800000e+01,NaN,4.0,4.0,2.0,1.0,...,2.0,1.0,2.0,2.0,1.0,3967.693106,4099.841985,1.0,171.0,5.000000e+00
33,109296.0,66.0,2.0,1.0,1.000000e+01,NaN,4.0,4.0,1.0,1.0,...,2.0,1.0,2.0,2.0,NaN,2515.973672,2743.675900,2.0,156.0,2.340000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15551,124814.0,66.0,2.0,1.0,6.400000e+01,NaN,4.0,4.0,2.0,1.0,...,2.0,1.0,2.0,2.0,1.0,3686.240810,3866.882086,1.0,171.0,2.000000e+00
15552,124815.0,66.0,2.0,1.0,5.200000e+01,NaN,4.0,4.0,2.0,1.0,...,2.0,1.0,2.0,2.0,1.0,24851.430976,27768.450036,1.0,172.0,5.000000e+00
15555,124818.0,66.0,2.0,1.0,4.000000e+01,NaN,4.0,4.0,1.0,1.0,...,2.0,1.0,2.0,2.0,1.0,21586.596728,21666.889837,1.0,166.0,3.820000e+00
15556,124819.0,66.0,2.0,1.0,2.000000e+00,NaN,4.0,4.0,2.0,1.0,...,2.0,NaN,NaN,NaN,NaN,1664.919253,1838.169709,2.0,171.0,7.000000e-02
15558,124821.0,66.0,2.0,1.0,6.300000e+01,NaN,4.0,4.0,1.0,1.0,...,2.0,1.0,2.0,2.0,1.0,4666.817952,4853.430230,1.0,158.0,3.710000e+00

In [55]:
race = df.groupby("RIDRETH3")[

In [56]:
df.plot.scatter(x = race, y = df[], alpha=.6)